# Deployment for App 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app3-html

---
# ConfigMap with HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>App 3 - Default</title>
        <style>
            body {
                background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
                color: white;
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }
            .container {
                text-align: center;
                background: rgba(255,255,255,0.1);
                padding: 50px;
                border-radius: 20px;
                box-shadow: 0 8px 32px rgba(0,0,0,0.3);
            }
            h1 { font-size: 3em; margin: 0; }
            p { font-size: 1.5em; }
            .default {
                background: rgba(255,255,255,0.3);
                padding: 10px 20px;
                border-radius: 25px;
                display: inline-block;
                margin-top: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🌐 Application 3</h1>
            <div class="default">
                <p style="margin: 0;">📍 DEFAULT APPLICATION</p>
            </div>
            <p>This app is shown when no host matches</p>
            <p style="font-size: 1em;">
                Access via IP: 192.168.56.110
            </p>
        </div>
    </body>
    </html>

---
# Service for App 3
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: app3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80