Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.define "rel-ismaS" do |server|
    server.vm.hostname = "rel-ismaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "rel-ismaS"
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Install K3s
    server.vm.provision "shell", path: "scripts/install_k3s.sh"
    
    # Deploy applications
    server.vm.provision "shell", path: "scripts/deploy_apps.sh"
  end
end